export const ServicesData = [
  {
    id: 1,
    title: "Organic Products",
    image: "fresh.png",
    desc: "Explore a world of organic treasure at our grocery store",
  },
  {
    id: 2,
    title: "Get Fresh Products",
    image: "fresh.png",
    desc: "Find a range of best online organic and fresh product",
  },
  {
    id: 3,
    title: "Fast Delivery",
    image: "free.png",
    desc: "Your Grocery items deliver to your doorstep quicker than ever",
  },
  {
    id: 4,
    title: "Safe Payment",
    image: "card.png",
    desc: "We are using secure payment methods",
  },
  {
    id: 5,
    title: "24/7 Service",
    image: "hours.png",
    desc: "Round the clock convience, shop anytime",
  },
  {
    id: 6,
    title: "Cash on delivery",
    image: "cash.png",
    desc: "Round the clock convience, shop anytime",
  },
  {
    id: 7,
    title: "Cash on delivery",
    image: "cash.png",
    desc: "Round the clock convience, shop anytime",
  },
  {
    id: 8,
    title: "Cash on delivery",
    image: "cash.png",
    desc: "Round the clock convience, shop anytime",
  },
];

export const HeroData = [
  {
    id: 1,
    title: "Fresh & Organic Groceries",
    subTitle: "For Healthy Life",
    desc: "Having a well-planned grocery lists gets you in and out of the store quickly and help you",
    button: "Shop Now",
    cover: "gro.png",
    link: "/category/vegetables",
  },
  {
    id: 2,
    title: "Stay @ Home & Order",
    subTitle: "For Your Best Groceries",
    desc: "Having a well-planned grocery lists gets you in and out of the store quickly and help you",
    button: "Order Now",
    cover: "order.png",
    link: "/category/fruits",
  },
  {
    id: 3,
    title: "Door 2 Door Delivery",
    subTitle: "Fastest Delivery & Easy Pickup",
    desc: "Having a well-planned grocery lists gets you in and out of the store quickly and help you",
    button: "Shop Now",
    cover: "delivery.png",
    link: "/support",
  },
  // {
  //   id: 1,
  //   title: "",
  //   subTitle: "",
  //   desc: "Having a well-planned grocery lists gets you in and out of the store quickly and help you",
  //   button: "Shop Now",
  //   cover: "",
  //   color: "",
  // },
];


export const TopProducts = [
  {
    id: 1,
    name: "Peach",
    price: 20,
    discount: 4,
    image: "peach.jpg",
    rating: 4,
  },
  {
    id: 2,
    name: "Strawberry",
    price: 20,
    discount: 3.5,
    image: "Strawberry.jpeg",
    rating: 3.5,
  },
  {
    id: 3,
    name: "Cabbage",
    price: 20,
    discount: 4.5,
    image: "cabbage.jpg",
    rating: 2.5,
  },
  {
    id: 4,
    name: "Apple",
    price: 20,
    discount: 5,
    image: "apple.jpg",
    rating: 4.5,
  },
  {
    id: 5,
    name: "Chicken Part",
    price: 20,
    discount: 4.8,
    image: "chickenpart.jpg",
    rating: 5,
  },
  {
    id: 6,
    name: "Steak",
    price: 20,
    discount: 4,
    image: "Steak.jpg",
    rating: 3.5,
  },
  {
    id: 7,
    name: "Raw Pork",
    price: 20,
    discount: 3.6,
    image: "rawpork.jpg",
    rating: 4.5,
  },
  {
    id: 8,
    name: "Grapes",
    price: 20,
    discount: 7,
    image: "grapes.jpg",
    rating: 2.5,
  },
  {
    id: 9,
    name: "Tomatoes",
    price: 20,
    discount: 5.5,
    image: "tomatoes.jpeg",
    rating: 3,
  },
  {
    id: 10,
    name: "Pineapple",
    price: 20,
    discount: 4,
    image: "pineapple2.jpg",
    rating: 3.5,
  },
  {
    id: 11,
    name: "Cluster Eggs",
    price: 20,
    discount: 4.8,
    image: "clustereggplant.jpg",
    rating: 5,
  },
  {
    id: 12,
    name: "Beef",
    price: 20,
    discount: 5,
    image: "beef.jpeg",
    rating: 4.5,
  },
  {
    id: 13,
    name: "Banana",
    price: 20,
    discount: 4.9,
    image: "banana.webp",
    rating: 3.5,
  },
  {
    id: 14,
    name: "Garlic",
    price: 20,
    discount: 4.6,
    image: "garlic.jpg",
    rating: 3.5,
  },
  {
    id: 15,
    name: "Sirloin",
    price: 20,
    discount: 3.5,
    image: "sirloin.jpg",
    rating: 3,
  },
  {
    id: 16,
    name: "Mango",
    price: 20,
    discount: 6,
    image: "mango.jpg",
    rating: 4.5,
  },
  {
    id: 17,
    name: "Onions",
    price: 20,
    discount: 4,
    image: "onions.jpg",
    rating: 3.5,
  },
  {
    id: 18,
    name: "Guava",
    price: 20,
    discount: 4.5,
    image: "guava.jpg",
    rating: 4.5,
  },
  {
    id: 19,
    name: "Gourmet",
    price: 20,
    discount: 4,
    image: "gourmet.jpg",
    rating: 3.5,
  },
  {
    id: 20,
    name: "Sugar Apple",
    price: 20,
    discount: 4.9,
    image: "sugarapple.jpg",
    rating: 5,
  },
];

export const Choose = [
  {
    id: 1,
    image: "bag.png",
    text: "Fresh and Organic Products",
  },
  {
    id: 2,
    image: "fresh.png",
    text: "Fresh and locally Grown products",
  },
  {
    id: 3,
    image: "free.png",
    text: "Fast delivery across nationwide",
  },
];

export const ContactData = [
  {
    title: "Leave us a message",
    header: "Get In Touch",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id fuga vel nesciunt eos  Id fuga vel nesciunt eos",
    connects: [
      {
        icon: "gmail.png",
        text: "Email: Info@GroceriesStore.com",
        info: "Info@GroceriesStore.com",
      },

      {
        icon: "call.png",
        tel: "Phone: +233 33 456 567",
        num: "+233 33 478 6495",
      },
      {
        icon: "location.png",
        text: "Address: Kumasi - Ghana",
        visit: "PremPeh II Street - Adum",
      },
    ],
  },
];
