export const Products = [
  {
    id: 1,
    name: "Mango",
    price: 10,
    image: "mango.jpg",
  },
  {
    id: 2,
    name: "Apple",
    price: 10,
    image: "apple.jpg",
  },
  {
    id: 3,
    name: "Banana",
    price: 10,
    image: "banana.webp",
  },
  {
    id: 4,
    name: "Peach",
    price: 10,
    image: "peach.jpg",
  },
  {
    id: 5,
    name: "Lemon",
    price: 10,
    image: "lemon2.jpg",
  },
  {
    id: 6,
    name: "Cherry",
    price: 10,
    image: "cherry.jpg",
  },
  {
    id: 7,
    name: "Strawberry",
    price: 10,
    image: "strawberry.jpeg",
  },
  {
    id: 8,
    name: "PawPaw",
    price: 10,
    image: "pawpaw.jpg",
  },
  {
    id: 9,
    name: "Pear",
    price: 10,
    image: "pear.jpg",
  },
  {
    id: 10,
    name: "Blackberry",
    price: 10,
    image: "Blackberry.png",
  },
  {
    id: 11,
    name: "Pineapple",
    price: 10,
    image: "pineapple2.jpg",
  },
  {
    id: 12,
    name: "Grapes",
    price: 10,
    image: "grapes.jpg",
  },
  {
    id: 13,
    name: "Orange",
    price: 10,
    image: "orange.webp",
  },
  {
    id: 14,
    name: "Watermelon",
    price: 10,
    image: "watermelon.webp",
  },
  {
    id: 15,
    name: "Avocado",
    price: 10,
    image: "pear.webp",
  },
  {
    id: 16,
    name: "JackFruit",
    price: 10,
    image: "jackfruit.jpg",
  },
  {
    id: 17,
    name: "Kiwi",
    price: 10,
    image: "kiwi.png",
  },
  {
    id: 18,
    name: "Coconut",
    price: 10,
    image: "coconut3.jpg",
  },
  {
    id: 19,
    name: "Guava",
    price: 10,
    image: "guava.jpg",
  },
  {
    id: 20,
    name: "Sugar Apple",
    price: 10,
    image: "sugarapple.jpg",
  },
  {
    id: 21,
    name: "Tangerines",
    price: 10,
    image: "tangerines.jpg",
  },
  {
    id: 22,
    name: "Cabbage",
    price: 10,
    image: "cabbage.jpg",
  },
  {
    id: 23,
    name: "Cauliflower",
    price: 10,
    image: "cauliflower.jpeg",
  },
  {
    id: 24,
    name: "Tomatoes",
    price: 10,
    image: "tomatoes.jpeg",
  },
  {
    id: 25,
    name: "Carrot",
    price: 10,
    image: "carrot.webp",
  },
  {
    id: 26,
    name: "Vegetables Beans",
    price: 10,
    image: "vegetablebeans.webp",
  },
  {
    id: 27,
    name: "Onions",
    price: 10,
    image: "onions.jpg",
  },
  {
    id: 28,
    name: "Pepper",
    price: 10,
    image: "pepper.png",
  },
  {
    id: 29,
    name: "Green Pepper",
    price: 10,
    image: "greenpepper.jpg",
  },
  {
    id: 30,
    name: "Cocumber",
    price: 10,
    image: "cocumber.jpeg",
  },
  {
    id: 31,
    name: "Garlic",
    price: 10,
    image: "garlic.jpg",
  },
  {
    id: 32,
    name: "Fresh Sayur",
    price: 10,
    image: "freshsayur.jpg",
  },
  {
    id: 33,
    name: "Broccoli",
    price: 10,
    image: "broccoli.jpg",
  },
  {
    id: 34,
    name: "Egg Plant",
    price: 10,
    image: "eggplant.jpg",
  },
  {
    id: 35,
    name: "Cluster Eggs",
    price: 10,
    image: "clustereggplant.jpg",
  },
  {
    id: 36,
    name: "Lettuce Leafs",
    price: 10,
    image: "lettuce2.jpg",
  },

  {
    id: 37,
    name: "Beef",
    price: 10,
    image: "beef.jpeg",
  },
  {
    id: 38,
    name: "Chicken",
    price: 10,
    image: "chicken.jpeg",
  },
  {
    id: 39,
    name: "Steak",
    price: 10,
    image: "steak.jpg",
  },
  {
    id: 40,
    name: "Raw Pork",
    price: 10,
    image: "rawpork.jpg",
  },
  {
    id: 41,
    name: "Strip Roast",
    price: 10,
    image: "striproast.jpg",
  },
  {
    id: 42,
    name: "Chicken Parts",
    price: 10,
    image: "chickenpart.jpg",
  },
  {
    id: 43,
    name: "Gourment",
    price: 10,
    image: "gourmet.jpg",
  },
  {
    id: 44,
    name: "Ribeye Roll",
    price: 10,
    image: "ribeyeroll.jpg",
  },
  {
    id: 45,
    name: "Sirloin",
    price: 10,
    image: "sirloin.jpg",
  },
  {
    id: 46,
    name: "Chicken Wings",
    price: 10,
    image: "chickenwings.jpg",
  },
  {
    id: 47,
    name: "Rib Steak",
    price: 10,
    image: "ribskeak.jpg",
  },
  {
    id: 48,
    name: "Chuckarm Roast",
    price: 10,
    image: "chuckarmroast.jpg",
  },
  {
    id: 49,
    name: "Chicken Liver",
    price: 10,
    image: "chickenliver.jpg",
  },
  {
    id: 50,
    name: "Chuck Neck",
    price: 10,
    image: "chuckneck.jpg",
  },
  {
    id: 51,
    name: "Brisket",
    price: 10,
    image: "brisket.jpg",
  },
  {
    id: 52,
    name: "Chuck Tender",
    price: 10,
    image: "chucktender.jpg",
  },
  {
    id: 53,
    name: "Gizzard",
    price: 10,
    image: "gizzard.jpg",
  },
  {
    id: 54,
    name: "Steak",
    price: 10,
    image: "steak.jpg",
  },
  {
    id: 55,
    name: "Bread",
    price: 10,
    image: "bread.jpg",
  },
  {
    id: 56,
    name: "Butter Cookies",
    price: 10,
    image: "buttercookies.png",
  },
  {
    id: 57,
    name: "Batticuori",
    price: 10,
    image: "batticuori.jpg",
  },
  {
    id: 58,
    name: "Sliced Bread",
    price: 10,
    image: "slicedbread.jpg",
  },
  {
    id: 59,
    name: "Chocolate",
    price: 10,
    image: "chocolatecookies.jpg",
  },
  {
    id: 60,
    name: "Oblong",
    price: 10,
    image: "oblong.jpg",
  },
  {
    id: 61,
    name: "Crostata",
    price: 10,
    image: "crostata.jpg",
  },
  {
    id: 62,
    name: "Icecream Ball",
    price: 10,
    image: "icecreamball.png",
  },
  {
    id: 63,
    name: "Chocolate Sauce",
    price: 10,
    image: "chocolatesauce.jpg",
  },
  {
    id: 64,
    name: "Scoops",
    price: 10,
    image: "scoops.png",
  },
  {
    id: 65,
    name: "Scoop Wafer",
    price: 10,
    image: "scoopwafer.png",
  },
  {
    id: 66,
    name: "Blue Bell",
    price: 10,
    image: "bluebell.jpg",
  },
  {
    id: 67,
    name: "Lemon Bar",
    price: 10,
    image: "lemonbar.png",
  },
  {
    id: 68,
    name: "Milkiest",
    price: 10,
    image: "milkiest.jpg",
  },
  {
    id: 69,
    name: "Peanut Butter",
    price: 10,
    image: "peanut.jpg",
  },
  {
    id: 70,
    name: "Strawberry",
    price: 10,
    image: "strawberry.jpg",
  },
  {
    id: 71,
    name: "Cereal Milk",
    price: 10,
    image: "cerealmilk.png",
  },
  {
    id: 72,
    name: "Vanilla",
    price: 10,
    image: "vanilla.jpg",
  },
  {
    id: 73,
    name: "Banana",
    price: 10,
    image: "banana.jpg",
  },
];
